name: SwimmingFins
version: '1.2'
main: com.ashkiano.swimmingFins.SwimmingFins
api-version: '1.16'
authors: [AshKiano]
commands:
  swimmingFins:
    description: Gives the player a pair of swimming fins.